### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by copurxia** [honue/MoviePilot-Plugins#1]
是因为刚入库之前有频繁读写的原因吗？
```
12:08:50.750 Execution Date: 2023-11-25 12:08:50
12:08:50.886 [https @ 0x1889800] HTTP error 403 Forbidden
12:08:50.886 https://resources.ani.rip/2023-10/[ANi] 堤亞穆帝國物語～從斷頭台開始，公主重生後的逆轉人生～ - 04 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4?d=true: Server returned 403 Forbidden (access denied)
12:08:50.887 EXIT
```

**Comment by honue** [comment]
你这个log是哪里的 emby server吗？我浏览器下载测试的没问题，emby需要设置http_proxy. 源是来自gd和cf境外网络需要挂梯. 刚刚才看到ani open的作者回我邮件了，我看看是不是屏蔽了emby的UA。

**Comment by copurxia** [comment]
我也是浏览器下载测试没问题，我猜是入库的时候有大量的频繁访问导致403了，我打算明天再看看，emby在nas上

**Comment by honue** [comment]
刚刚我这emby测试成功了，建议检查emby代理设置是否按readme所述设置。

**Comment by honue** [comment]
不是的。生成这些strm文件只和ani open通信了一次 ，http格式是固定的，一次性就拿到了所有当季的文件名，根据文件名批量生成的http链接。只有你正式播放才会再次对ani open发起网络请求。

**Comment by copurxia** [comment]
代理设置我觉得是没问题的，我看了下clash的后台他成功走代理了
![image](https://github.com/honue/MoviePilot-Plugins/assets/53603471/621f4471-3ac1-4c65-b438-fc37c7602dbb)

**Comment by honue** [comment]
刚刚回ani open作者邮件去了，我这边正常使用，建议检查梯子ip网络问题?
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/6d4ee59b-d9df-4684-9b75-89d44a3c1def)

**Comment by copurxia** [comment]
发现问题了，我试着本地连接代理，触发了cf盾

**Comment by honue** [comment]
（苟着点，刚刚让ani open作者那边去看看访问ua多不多，多的话通知我，我这个转private。

**Comment by copurxia** [comment]
嗯

**Comment by copurxia** [comment]
今天正常了，标记一下（没有任何修改）

**Comment by honue** [comment]
ok

**Comment by honue** [comment]
这个插件还有点问题，1那个重试机制可以用装饰器来完成，2.最新top应该从https://api.ani.rip/ani-download.xml获取top，单一季度会抓不到跨季度更新的番剧，有能力的话欢迎pr，我目前没时间改。。
