### ISSUE TITLE
Ani strm 无法生成 top 15

### ISSUE THREAD

**Issue by shiji5824666** [honue/MoviePilot-Plugins#10]
WARNING: anistrm - 未获取到文件信息，3秒后重试 ...
WARNING: anistrm - 未获取到文件信息，3秒后重试 ...
WARNING: anistrm - 未获取到文件信息，3秒后重试 ...
WARNING: anistrm - https://aniopen.an-i.workers.dev/ 请确保当前季度番剧文件夹存在
INFO:    anistrm - 本次处理 0 个文件
INFO:    anistrm - 新创建了 0 个strm文件

log如上，如果不勾选“下次创建当前季度所有番剧strm” 就无法生成 top 15

INFO:    anistrm - 本次处理 313 个文件
INFO:    themoviedb - 梦想成为魔法少女 使用TMDB识别缓存：憧憬成为魔法少女
INFO:    tmdbapi.py - 正在查询TMDB电视剧：236338 ...
INFO:    anistrm - 新创建了 313 个strm文件
INFO:    tmdbapi.py - 236338 查询结果：憧憬成为魔法少女
INFO:    themoviedb - 梦想成为魔法少女 TMDB识别结果：电视剧 憧憬成为魔法少女 (2024) 236338
INFO:    dirmonitor - [ANi] 夢想成為魔法少女 [年齡限制版] - 09 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4.strm 识别为：电视剧 憧憬成为魔法少女 (2024)

log如上，如果勾选“下次创建当前季度所有番剧strm”，功能就生效了

resources.ani.rip
aniopen.an-i.workers.dev
api.ani.rip
ani.rip
这四条都放进代理列表了，请问大佬还需要做什么吗，谢谢答复！

**Comment by kai456789** [comment]
遇到一樣的問題
【WARNING】2024-03-06 01:20:09,567 - bahastrm - https://aniopen.an-i.workers.dev/ 請確保當前季度番劇資料夾存在
【INFO】2024-03-06 01:20:09,568 - bahastrm - 本次處理 0 個檔案
【INFO】2024-03-06 01:20:09,569 - bahastrm - 新建立了 0 個strm檔案
【WARNING】2024-03-06 01:40:00,040 - bahastrm - 未獲取到檔案資訊，3秒後重試 ...
【WARNING】2024-03-06 01:40:03,065 - bahastrm - 未獲取到檔案資訊，3秒後重試 ...
【WARNING】2024-03-06 01:40:06,088 - bahastrm - 未獲取到檔案資訊，3秒後重試 ...
【WARNING】2024-03-06 01:40:09,089 - bahastrm - https://aniopen.an-i.workers.dev/ 請確保當前季度番劇資料夾存在
【INFO】2024-03-06 01:40:09,090 - bahastrm - 本次處理 0 個檔案
【INFO】2024-03-06 01:40:09,091 - bahastrm - 新建立了 0 個strm檔案

**Comment by honue** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/b29295b5-b495-4a74-b6a5-abde753bfe0e)
我这测试正常

**Comment by shiji5824666** [comment]
> ![image](https://private-user-images.githubusercontent.com/57806936/310441274-b29295b5-b495-4a74-b6a5-abde753bfe0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTk1ODksIm5iZiI6MTcwOTcxOTI4OSwicGF0aCI6Ii81NzgwNjkzNi8zMTA0NDEyNzQtYjI5Mjk1YjUtYjQ5NS00YTc0LWI2YTUtYWJkZTc1M2JmZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEwMDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYWY1MzA4NTcxZDQ1MmYyNTdiODA5OGMwZDVkOWQ0MTk3OTY5OTI3OTVjZjMxMDdhNmQ1NDJkYmQ4MTUyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C5AnqF69xO9xn1x_lt3hD5PTlGFwrIgamL2KMxer_I8) 我这测试正常

我这里测试，一次性抓取全季度没问题，定时任务失败；一次性抓取最新失败，定时任务失败；如果是梯子问题，为什么一次性抓取全季度成功了，这就很奇怪......

**Comment by honue** [comment]
https://api.ani.rip/ani-download.xml

**Comment by shiji5824666** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/64516590/50303672-08a5-4263-83b2-ae7c3e2e1145)
![image](https://github.com/honue/MoviePilot-Plugins/assets/64516590/def1d24e-b83b-4ed9-a5e2-2d29f759b57f)
网络联通性都正常，也能进去网页，passwall开到全局代理，还是报同样的错。

**Comment by honue** [comment]
> https://api.ani.rip/ani-download.xml

top追新是这个地址 logger给的信息我没改

**Comment by shiji5824666** [comment]
> > https://api.ani.rip/ani-download.xml
> 
> top追新是这个地址 logger给的信息我没改

![image](https://github.com/honue/MoviePilot-Plugins/assets/64516590/b119e8d5-d150-4098-850e-28721b4ed139)
![image](https://github.com/honue/MoviePilot-Plugins/assets/64516590/90916334-385e-42c1-b2f5-3667d8f1c289)

这个地址可以直连，但是报的错不是这个地址，测试的版本号是2.2

**Comment by honue** [comment]
log信息我没改…上次忘了也懒得再改了 这个地址走代理

**Comment by shiji5824666** [comment]
不是代理的问题吧，我开全局代理都没用的，而且这个地址直连都没问题

**Comment by shiji5824666** [comment]
> log信息我没改…上次忘了也懒得再改了 这个地址走代理

直连居然成功了，走代理反而不行
