### ISSUE TITLE
自适应IntroSkip插件报错，网页端和小秘客户端均报错，emby版本 4.8.0.69 测试版

### ISSUE THREAD

**Issue by qhly2010** [honue/MoviePilot-Plugins#11]
【ERROR】2024-03-04 03:37:40,773 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2d52b390>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:40,980 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/emby/Items/None/PlaybackInfo?api_key=8f8ac70176744513b7f78884394ee62b (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2cc424d0>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:51,607 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2d393b90>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:51,789 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/emby/Items/None/PlaybackInfo?api_key=8f8ac70176744513b7f78884394ee62b (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d320f0a10>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:51,990 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d31992410>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:56,517 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2cc94b10>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:56,549 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2d1acbd0>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:56,720 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/emby/Items/None/PlaybackInfo?api_key=8f8ac70176744513b7f78884394ee62b (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2cc94250>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:56,735 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/emby/Items/None/PlaybackInfo?api_key=8f8ac70176744513b7f78884394ee62b (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2cba9510>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:56,904 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2dda5610>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:37:56,932 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2cebd9d0>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:38:07,300 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2cc16b10>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:38:07,486 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/emby/Items/None/PlaybackInfo?api_key=8f8ac70176744513b7f78884394ee62b (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2cc17750>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
【ERROR】2024-03-04 03:38:07,664 - SkipHelper.py - 异常错误：HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.101.201:28096/Shows/132105/Episodes (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f6d2d9ba290>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))

**Comment by honue** [comment]
mp emby_host 参数设置为IP:PORT 不需要带http
