### ISSUE TITLE
豆瓣书影音档案同步异常

### ISSUE THREAD

**Issue by richamon** [honue/MoviePilot-Plugins#12]
实际试了下没有效果,看了代码好像只涉及emby,是否会增加对plex的支持~感谢

**Comment by honue** [comment]
可能是username那块你没填好？我没有plex无法测试，你看看能否带上webhook的日志

**Comment by richamon** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/20623652/069801a9-a203-4670-909c-6fc634ced5f7)
插件日志如上,已获取到观看记录(非第一集,都是点的后边某一集),但未同步到豆瓣进行标记,已经将 douban.com 加入到cookiecloud同步

**Comment by honue** [comment]
@richamon 好的，估计是哪里我plex if写错了，下个礼拜改，最近我没有空，更新了我会在这留言。webhook能拿到播放信息就不是大事。

**Comment by saarjoye** [comment]
emby播放后。插件日志也显示获取到豆瓣subject_id。但是豆瓣没有同步到记录。是否有其它配置

**Comment by honue** [comment]
@saarjoye @richamon 刚刚推了1.1，你重启docker 更新下插件看看报错，我的cookie是自建docker，我不知道是不是跟mp内建cookiecloud的cookie获取有关

**Comment by saarjoye** [comment]
我用的也是自建的cookiecloud

**Comment by honue** [comment]
这个礼拜我实在是没时间，刚刚加了两个doubanhelper的logger，你们自行看着排查。解决不了的话，把logger贴这个，我复试完来看看什么原因。

**Comment by saarjoye** [comment]
好的谢谢您

**Comment by honue** [comment]
正常
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/af3a6c2f-bfb7-459f-bb63-519ca1756b3e)
不正常
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/f163dc7b-d014-4af3-bccd-6e678621d32b)

我这也出问题了，我回头看看，这个插件暂时用不了，先放放吧

**Comment by saarjoye** [comment]
我删除后想重新安装新版本。结果插件库里找不到了

**Comment by honue** [comment]
> 实际试了下没有效果,看了代码好像只涉及emby,是否会增加对plex的支持~感谢

与plex无关，豆瓣那边做了限制，回头我看看

**Comment by 7-orion** [comment]
用了新版本1.2 好像还没好 不知道是不是我自己设置有问题

**Comment by honue** [comment]
> 用了新版本1.2 好像还没好 不知道是不是我自己设置有问题

还没好，我昨天才复试完，在住的地方临时看了下，电脑上测得没问题，我回家看看nas具体啥问题

**Comment by honue** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/b18db143-f6b8-44af-87ba-e825b0257474)
@richamon @7-orion @saarjoye 
不知道是不是cookie的问题，我这又可以了，然后稍微改了下，现在不用cookie去搜索，现在看看1.3版本获取豆瓣id是否正常

**Comment by saarjoye** [comment]
> ![image](https://private-user-images.githubusercontent.com/57806936/318370956-b18db143-f6b8-44af-87ba-e825b0257474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjA2ODcsIm5iZiI6MTcxMTk2MDM4NywicGF0aCI6Ii81NzgwNjkzNi8zMTgzNzA5NTYtYjE4ZGIxNDMtZjZiOC00NGFmLTg3YmEtZTgyNWIwMjU3NDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA4MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZDE4OGY5M2EzMjE3ZTZiNzk5ZjcwZWZhODdiODVkZjJmNGQyNDQ1MTg3NWZmMTgxNzk5OGI2NWU0NzFmN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r4PffWxdDlvJOK63S-77TGf0SvUssC5cu4l0iGMZ9u4) @richamon @7-orion @saarjoye 不知道是不是cookie的问题，我这又可以了，然后稍微改了下，现在不用cookie去搜索，现在看看1.3版本获取豆瓣id是否正常

我点更新报错。然后删掉插件想重装。结果插件库里找不到了

**Comment by honue** [comment]
@saarjoye 你把容器删了 再建一个试试，你是群晖吗，重构一下容器

**Comment by saarjoye** [comment]
> @saarjoye 你把容器删了 再建一个试试，你是群晖吗，重构一下容器

我是群晖，是显示所有插件库都连接不上。但是我测试科学环境都是通的，好像提示一个超时什么的

**Comment by saarjoye** [comment]
> @saarjoye 你把容器删了 再建一个试试，你是群晖吗，重构一下容器

我是群晖，是显示所有插件库都连接不上。但是我测试科学环境都是通的
![Uploading image.png…]()
提示这个

**Comment by saarjoye** [comment]
403 -rate limit exceeded

**Comment by honue** [comment]
> 403 -rate limit exceeded

填下 GitHub-token参数

**Comment by honue** [comment]
在这获取，https://github.com/settings/tokens ，classic那个生成一个新的

**Comment by 7-orion** [comment]
大佬已更新1.3，仍然是之前的问题…我用的是pve的lxc

**Comment by 7-orion** [comment]
【INFO】2024-04-01 16:26:29,312 - doubanwatching - 开始尝试获取 超异能族 豆瓣subject_id
【INFO】2024-04-01 16:26:29,310 - doubanwatching - 开始播放 超异能族 第1季 第14集
【INFO】2024-04-01 10:36:00,704 - doubanwatching - 开始尝试获取 超异能族 豆瓣subject_id
【INFO】2024-04-01 10:36:00,702 - doubanwatching - 开始播放 超异能族 第1季 第14集
【INFO】2024-04-01 01:21:26,376 - doubanwatching - 开始尝试获取 超异能族 豆瓣subject_id
【INFO】2024-04-01 01:21:26,373 - doubanwatching - 开始播放 超异能族 第1季 第13集

**Comment by honue** [comment]
> 大佬已更新1.3，仍然是之前的问题…我用的是pve的lxc

不会吧...

**Comment by saarjoye** [comment]
> 在这获取，https://github.com/settings/tokens ，classic那个生成一个新的

生成新的。有好多选项要勾。我是全选勾吗

**Comment by saarjoye** [comment]
这个github token我已经处理好了。其它插件已经可以正常安装。但是插件列表里找不到豆瓣书影音档案这个插件了

**Comment by honue** [comment]
> 这个github token我已经处理好了。其它插件已经可以正常安装。但是插件列表里找不到豆瓣书影音档案这个插件了

你看看加没加我这个仓库的地址

**Comment by saarjoye** [comment]
> > 这个github token我已经处理好了。其它插件已经可以正常安装。但是插件列表里找不到豆瓣书影音档案这个插件了
> 
> 你看看加没加我这个仓库的地址

有的。我去确认了下。存在的

**Comment by saarjoye** [comment]
https://github.com/honue/MoviePilot-Plugins

**Comment by honue** [comment]
> 大佬已更新1.3，仍然是之前的问题…我用的是pve的lxc

你是通过网页手动更新的吗，我不确定是不是会更新 helper py文件，你要不试试重新构建容器

> > > 这个github token我已经处理好了。其它插件已经可以正常安装。但是插件列表里找不到豆瓣书影音档案这个插件了
> > 
> > 
> > 你看看加没加我这个仓库的地址
> 
> 有的。我去确认了下。存在的

tg联系我远程看看？

**Comment by honue** [comment]
> 大佬已更新1.3，仍然是之前的问题…我用的是pve的lxc

你是通过网页手动更新的吗，我不确定这样是不是会更新 helper py文件，你要不试试重新构建容器，如果有报错应该会有更多的日志呀

**Comment by saarjoye** [comment]
我重构容器后现在有了。我现在测试下

**Comment by saarjoye** [comment]
![微信图片_20240401171020](https://github.com/honue/MoviePilot-Plugins/assets/76988802/58217fa7-8d7b-4eae-a4f5-51321a9f5476)
好像还是不行

**Comment by saarjoye** [comment]
【INFO】2024-04-01 17:10:11,022 - doubanwatching - 何以中国 同步到档案失败
【INFO】2024-04-01 17:10:10,766 - doubanwatching - 查询：何以中国 => 匹配豆瓣：何以中国 https://movie.douban.com/subject/35441874
【INFO】2024-04-01 17:09:49,691 - doubanwatching - 开始尝试获取 何以中国 豆瓣subject_id
【INFO】2024-04-01 17:09:49,689 - doubanwatching - 开始播放 何以中国 第1季 第2集

**Comment by honue** [comment]
> 【INFO】2024-04-01 17:10:11,022 - doubanwatching - 何以中国 同步到档案失败 【INFO】2024-04-01 17:10:10,766 - doubanwatching - 查询：何以中国 => 匹配豆瓣：何以中国 https://movie.douban.com/subject/35441874 【INFO】2024-04-01 17:09:49,691 - doubanwatching - 开始尝试获取 何以中国 豆瓣subject_id 【INFO】2024-04-01 17:09:49,689 - doubanwatching - 开始播放 何以中国 第1季 第2集

这就拿到豆瓣id了，你现在登录下网页版的豆瓣，再手动同步下cookiecloud

**Comment by saarjoye** [comment]
![微信图片_20240401171456](https://github.com/honue/MoviePilot-Plugins/assets/76988802/ca4480cc-43ed-4a17-b554-0ca88f22b90e)
是这样手动同步吗？我同步完还是同步档案失败

**Comment by honue** [comment]
> ![微信图片_20240401171456](https://private-user-images.githubusercontent.com/76988802/318393010-ca4480cc-43ed-4a17-b554-0ca88f22b90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjMyMzAsIm5iZiI6MTcxMTk2MjkzMCwicGF0aCI6Ii83Njk4ODgwMi8zMTgzOTMwMTAtY2E0NDgwY2MtNDNlZC00YTE3LWI1NTQtMGNhODhmMjJiOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA5MTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTJiYWEzNzJmOThhZGQ0NmI1N2Q4ZTUzZTEyMmEzMGJlZmRlODgzMTFmMmFhMjNlZTNiYmFhNDg0ODRiZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d1qUsR0LtAqFiaiaNooyJcJ6jiqABox_oeDXcOCMq00) 是这样手动同步吗？我同步完还是同步档案失败
10分钟后，重构容器，同步错误的加了log

**Comment by saarjoye** [comment]
是我需要重构MP吗？还是说重构cookiecloud

**Comment by honue** [comment]
@saarjoye 重构mp，自己检查下到底登录没有，这里应该是你自己的使用问题了，我不想在这块跟你大篇幅的展开，因为这里的讨论另外三个人都会收到邮件通知

**Comment by honue** [comment]
@richamon 你试试现在行不行？重构容器，这样会拉最新的插件代码

**Comment by 7-orion** [comment]
大佬重构容器后能报错了。
![Uploading Snipaste_2024-04-01_18-03-55.png…]()
这是啥原因…

**Comment by honue** [comment]
> 大佬重构容器后能报错了。 <img alt="Snipaste_2024-04-01_18-03-55" width="1918" src="https://private-user-images.githubusercontent.com/32628296/318403853-318cf4a7-b4c3-4017-8f7b-8d1cdf20b774.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjYyNDEsIm5iZiI6MTcxMTk2NTk0MSwicGF0aCI6Ii8zMjYyODI5Ni8zMTg0MDM4NTMtMzE4Y2Y0YTctYjRjMy00MDE3LThmN2ItOGQxY2RmMjBiNzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZGUzOGI4NDI0YjBhM2EzNjJkZjZiOWY2YjU5ZTA0OGQ3MmQ5YTlkMjM4NDM3NzljYTZmMmVkMDZkM2NmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1cHIkz4PUaGYMvSgkmdBqbVm-Tnrnm8NJf5cWCapCSg">
> 
> 这是啥原因…

@saarjoye 你应该也是这个问题
@7-orion 我研究下，我这没遇到不好调试，我看看具体什么原因 带了cookie还403，你可以先暂时重新登录下豆瓣再同步到cookiecloud，用最新的豆瓣cookie看看还会不会报错

**Comment by honue** [comment]
@saarjoye 方便留个tg吗，我想跟你私聊调试下

**Comment by 7-orion** [comment]
> > 大佬重构容器后能报错了。 <img alt="Snipaste_2024-04-01_18-03-55" width="1918" src="https://private-user-images.githubusercontent.com/32628296/318403853-318cf4a7-b4c3-4017-8f7b-8d1cdf20b774.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjYyNDEsIm5iZiI6MTcxMTk2NTk0MSwicGF0aCI6Ii8zMjYyODI5Ni8zMTg0MDM4NTMtMzE4Y2Y0YTctYjRjMy00MDE3LThmN2ItOGQxY2RmMjBiNzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMDU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZGUzOGI4NDI0YjBhM2EzNjJkZjZiOWY2YjU5ZTA0OGQ3MmQ5YTlkMjM4NDM3NzljYTZmMmVkMDZkM2NmZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1cHIkz4PUaGYMvSgkmdBqbVm-Tnrnm8NJf5cWCapCSg">
> > 这是啥原因…
> 
> @saarjoye 你应该也是这个问题 @7-orion 我研究下，我这没遇到不好调试，我看看具体什么原因 带了cookie还403，你可以先暂时重新登录下豆瓣再同步到cookiecloud，用最新的豆瓣cookie看看还会不会报错

我试了下，如果没操作错的话，应该重新登录了用了最新的cookie，但还是一样的报错

**Comment by honue** [comment]
> 我试了下，如果没操作错的话，应该重新登录了用了最新的cookie，但还是一样的报错 <img alt="Snipaste_2024-04-01_18-13-39" width="1913" src="https://private-user-images.githubusercontent.com/32628296/318405977-886528e5-c877-4468-835f-ef77a0abb27a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjY4MjksIm5iZiI6MTcxMTk2NjUyOSwicGF0aCI6Ii8zMjYyODI5Ni8zMTg0MDU5NzctODg2NTI4ZTUtYzg3Ny00NDY4LTgzNWYtZWY3N2EwYWJiMjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEwMTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzZmNTZkNzY4MmIxMWUxYWE4ZTJlZGY3NGQ5YzE1Y2FmNDVlMjU4MmFlNmY3MjBkZTFhODliM2M4MGNkMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Saep--c8of2wmFGUzSL_MNJOARqb9wPBOR-0SWkBmo8">

@7-orion 我大概知道问题所在了，刚刚看了下vt的代码，你方便留个tg吗？私下想让你调试下

**Comment by saarjoye** [comment]
![微信图片_20240401181849](https://github.com/honue/MoviePilot-Plugins/assets/76988802/e885ca92-b368-4597-b116-91c2169a8698)
 TG不是很会用。

**Comment by 7-orion** [comment]
<img width="376" alt="Snipaste_2024-04-01_18-27-51" src="https://github.com/honue/MoviePilot-Plugins/assets/32628296/f2d4ffed-2aa0-441b-966c-8c420ee1e162">

**Comment by honue** [comment]
fix #12 in https://github.com/honue/MoviePilot-Plugins/commit/8dfbc975e783e9f76a9fd8600b974b905af002a9

**Comment by zww94** [comment]
请我 填写了cookie 然后媒体裤名字也填写了，无任何日志，日志页面是空白

**Comment by amory1999** [comment]
大佬，plex支持同步吗，webhook  plex怎么设置呢

**Comment by voodooTTC** [comment]
我也是媒体库用户名和cookie都填了~看日志一直是空白？mp v2      。PLEX的webhooks也设置了。

**Comment by tclyg2008** [comment]
> > 请我 填写了cookie 然后媒体裤名字也填写了，无任何日志，日志页面是空白
> 
> 我解决了 已经好了。 附我的软件版本情况 emby4.8.11 MP2.5.3 豆瓣同步插件1.9.5 注意webhook要配置 媒体服务器的 然后注意吧mp的日志改成debug的 就可以看到这个插件日志了 祝你好运
老哥好，我的情况和您非常接近，有以下几个问题想请教：
1. emby中webhook具体配置的地址可否发来参考
2. douban使用cookiecloud同步还是手动填写
谢谢您

**Comment by CCC2749** [comment]
> > > 请我 填写了cookie 然后媒体裤名字也填写了，无任何日志，日志页面是空白
> > 
> > 
> > 我解决了 已经好了。 附我的软件版本情况 emby4.8.11 MP2.5.3 豆瓣同步插件1.9.5 注意webhook要配置 媒体服务器的 然后注意吧mp的日志改成debug的 就可以看到这个插件日志了 祝你好运
> > 老哥好，我的情况和您非常接近，有以下几个问题想请教：
> 
> 1. emby中webhook具体配置的地址可否发来参考
> 2. douban使用cookiecloud同步还是手动填写
>    谢谢您

A1:<img width="1395" height="811" alt="Image" src="https://github.com/user-attachments/assets/ecba7fb5-87c2-47ab-a47d-28d56976b23d" />
A2:用的cookiecloud  填写如果请求多了 容易失效

**Comment by voodooTTC** [comment]
<img width="835" height="339" alt="Image" src="https://github.com/user-attachments/assets/1fe26305-021c-4add-b2ae-21177c22787f" />
之前都正常。最近几天PLEX的观影记录就没有日志显示了。什么都没改动。豆瓣cookie也是cloud自动获取的。mpv2 2.7.8 豆瓣同步插件1.9.6
