### ISSUE TITLE
Ani Strm创建当前季度所有番剧strm成功，但无法获取本季度top15

### ISSUE THREAD

**Issue by chiluoyi** [honue/MoviePilot-Plugins#13]
开启下次创建当前季度所有番剧strm能够成功生成strm，但是关闭这个选项不会获取本季度top15，而是提示未获取到文件信息，3秒后重试

**Comment by honue** [comment]
上次有个issue也是这个问题

**Comment by chiluoyi** [comment]
> #10 我这测试正常

您好，我查看了日志，确认访问https://api.ani.rip/ani-download.xml是使用了代理的，依旧会无法生成top15，同链接里的说法一样，直连就能够成功。
在代理的情况下，通过浏览器访问https://api.ani.rip/ani-download.xml，会弹出cf盾，有没有可能是这个的原因？

**Comment by honue** [comment]
应该是吧，我这梯子ip没问题，回头我改下代理可选
