### ISSUE TITLE
豆瓣书影音档案同步bug

### ISSUE THREAD

**Issue by richamon** [honue/MoviePilot-Plugins#16]
获取剧集名字不完整 ,跳过了名字中的空格 ,海贼王 真人版 识别为 海贼王
![image](https://github.com/honue/MoviePilot-Plugins/assets/20623652/5c51040f-ff0b-44bb-8432-5bd8a3c8bdf7)
![image](https://github.com/honue/MoviePilot-Plugins/assets/20623652/690101b2-5e86-4974-a916-d5a70c03009c)

**Comment by honue** [comment]
没考虑到这个 我找时间再看看，或者就这样，要处理这个可能要用正则

**Comment by honue** [comment]
应该好了 你试试

**Comment by richamon** [comment]
感谢修复~已正常
