### ISSUE TITLE
豆瓣的webhook回调url填什么啊？

### ISSUE THREAD

**Issue by zero617** [honue/MoviePilot-Plugins#18]

**Comment by zero617** [comment]
tg群没人回-_- 佬帮忙看下这哪里错了
![Clip_2024-04-05_21-45-09](https://github.com/honue/MoviePilot-Plugins/assets/67105838/1819f288-c7ea-4349-baf2-3562040ec258)

**Comment by honue** [comment]
> tg群没人回-_- 佬帮忙看下这哪里错了 ![Clip_2024-04-05_21-45-09](https://private-user-images.githubusercontent.com/67105838/320018754-1819f288-c7ea-4349-baf2-3562040ec258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjUwNzcsIm5iZiI6MTcxMjMyNDc3NywicGF0aCI6Ii82NzEwNTgzOC8zMjAwMTg3NTQtMTgxOWYyODgtYzdlYS00MzQ5LWJhZjItMzU2MjA0MGVjMjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEzNDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MmUzMTRhYWE5MGQ2OTk0Y2JiZmZhOTQxMTVjZGFiMDA4MDUyY2VmNzRlYTMzMTcwNjAwN2M1MzU4YTIyODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p3gyA0t0w7tE80S3P_6wNH2YvjHetGSWu1tlsGSW1N8)

没加apikey 这个参数

**Comment by honue** [comment]
> http://127.0.0.1:3001/api/v1/webhook?token=your_key

@zero617 请你提问前，自己好好检查检查，思考思考，你这样随意的提问无异于在浪费我的时间，我并没有义务帮助你解决配置问题。话虽然直接了点，但请你理解。

**Comment by zero617** [comment]
> > http://127.0.0.1:3001/api/v1/webhook?token=your_key
> 
> @zero617 请你提问前，自己好好检查检查，思考思考，你这样随意的提问无异于在浪费我的时间，我并没有义务帮助你解决配置问题。话虽然直接了点，但请你理解。

抱歉抱歉，麻烦了，这是我的问题
api我之前就发现并修改了，我这个问题是以为emby用户已播放的行为也能同步过去 原来只有播放的行为会被同步
话说用户已播放的行为的同步是无法实现吗？

**Comment by honue** [comment]
> 抱歉抱歉，麻烦了，这是我的问题 api我之前就发现并修改了，我这个问题是以为emby用户已播放的行为也能同步过去 原来只有播放的行为会被同步 话说用户已播放的行为的同步是无法实现吗？

可以但我不想，你需要可以pr改改
