### ISSUE TITLE
Bangumi在看同步没有正常工作

### ISSUE THREAD

**Issue by TyxTang** [honue/MoviePilot-Plugins#19]
![image](https://github.com/honue/MoviePilot-Plugins/assets/90897955/686d2dad-6a90-44d2-a39f-2a3b0847a6a3)
安装了很久都只是同步过这两条，其余emby播放都无反应，豆瓣那边是能正常同步的（webhook没问题）
日志没有再动过

**Comment by honue** [comment]
```python
        if not BangumiSync.is_anime(path):
            # path_keyword = "cartoon,动漫,动画,ani,anime,新番,番剧,特摄"
            return

        if event_info.item_type in ["TV"] and \
                event_info.event in play_start and \
                event_info.user_name in self._user.split(','):
                pass
```

你看看是不是不满足这两个条件直接return了

**Comment by TyxTang** [comment]
> ```python
>         if not BangumiSync.is_anime(path):
>             # path_keyword = "cartoon,动漫,动画,ani,anime,新番,番剧,特摄"
>             return
> 
>         if event_info.item_type in ["TV"] and \
>                 event_info.event in play_start and \
>                 event_info.user_name in self._user.split(','):
>                 pass
> ```
> 
> 你看看是不是不满足这两个条件直接return了

```
def is_anime(path):
        """
        通过路径关键词来确定是不是anime媒体库
        """
        path_keyword = "cartoon,动漫,动画,ani,anime,新番,番剧,特摄"
        for keyword in path_keyword.split(','):
            if path.count(keyword):
                return True
        return False
```
我看了下源码，可不可以理解为emby动漫媒体文件的路径必须包含以上path_keyword关键词（我不太清楚webhook实际返回的内容

**Comment by honue** [comment]
是的，包含上述任意关键词，item_path是你emby中的媒体文件路径

**Comment by TyxTang** [comment]
感谢，问题已解决
