### ISSUE TITLE
《Bangumi在看同步》插件对plex似乎不生效?

### ISSUE THREAD

**Issue by GlowsSama** [honue/MoviePilot-Plugins#23]
moviepilot v1.8.1-1
Bangumi在看同步 v1.5.0

已填写媒体库用户名和bangumi的token
但是运行时插件页日志为空白

尝试过临时搭建emby 能正常获取到日志

**Comment by honue** [comment]
https://github.com/honue/MoviePilot-Plugins/blob/bf838d998b24d4128c21f81f4d5991faf64fbfcb/plugins/bangumisync/__init__.py#L51

没对plex做限制，我没plex，你看看plex是这几个event中的一个吧

**Comment by junyuyuan** [comment]
我使用emby，插件日志也是一片空白。
![image](https://github.com/honue/MoviePilot-Plugins/assets/11531378/b04ff0fa-daff-41d8-ba1c-628518fae64c)
![image](https://github.com/honue/MoviePilot-Plugins/assets/11531378/263dc4ea-6816-4d1f-a6c6-5fc132bc0020)

**Comment by junyuyuan** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/11531378/559370de-7feb-460c-967e-6ecb3b00f5f0)

**Comment by happyTonakai** [comment]
> ![image](https://private-user-images.githubusercontent.com/11531378/336287249-559370de-7feb-460c-967e-6ecb3b00f5f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDQ3MjUsIm5iZiI6MTcxNzk0NDQyNSwicGF0aCI6Ii8xMTUzMTM3OC8zMzYyODcyNDktNTU5MzcwZGUtN2ZlYi00NjBjLTk2N2UtNmVjYjNiMDBmNWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE0NDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3M2M4ZTJmYjI2ODAyZGFhMDA3Mzg2OWU3YjgyYTI5NDYyZGE0NTE1NmYzNDcwOTU2NWViNzFiODBjNmE3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R7YZfrzwvBv6MS9l-m3bMkYeNP0Bl-KDi0tr_iaxcSo)

下面勾选了哪些webhook事件？有成功发送测试通知吗

**Comment by happyTonakai** [comment]
> 我使用emby，插件日志也是一片空白。 ![image](https://private-user-images.githubusercontent.com/11531378/336286974-b04ff0fa-daff-41d8-ba1c-628518fae64c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDQ3MjUsIm5iZiI6MTcxNzk0NDQyNSwicGF0aCI6Ii8xMTUzMTM3OC8zMzYyODY5NzQtYjA0ZmYwZmEtZGFmZi00MWQ4LWJhMWMtNjI4NTE4ZmFlNjRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE0NDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYzlmMDc4MDFiZTQyZjc5NTFkMjMyODEwZGU2ZGYyZmQ0MGY3ZGZiNTQ3YTExZjNkMTZlZGNkN2M1YjA4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aHIFUf-WZw9VwBvN_d8132gHDJKfbvWc-BQLFwdhjDk) ![image](https://private-user-images.githubusercontent.com/11531378/336287056-263dc4ea-6816-4d1f-a6c6-5fc132bc0020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDQ3MjUsIm5iZiI6MTcxNzk0NDQyNSwicGF0aCI6Ii8xMTUzMTM3OC8zMzYyODcwNTYtMjYzZGM0ZWEtNjgxNi00ZDFmLWE2YzYtNWZjMTMyYmMwMDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE0NDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZWQwMzcwNGU3MWFjYThlNmIxZWVjODE0NTc3MDBiMTNlZDI3OTE2ZDAzOTJkYWJmNmRkOTMzY2NiY2Y1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R_iOOsbCpcNgXAtBVrDXM-QrxOcOxD2sQFyB-gw9ais)

DEBUG模式开一下试试？初始化、收到webhook现在都是debug级别的日志，还有你的文件路径（在emby中的映射）是啥，有没有包含这些关键词：cartoon,动漫,动画,ani,anime,新番,番剧,特摄,bangumi,ova,映画,国漫,日漫

**Comment by honue** [comment]
no response
