### ISSUE TITLE
ANi-Strm插件在市场里找不到！

### ISSUE THREAD

**Issue by Awhitedressy** [honue/MoviePilot-Plugins#24]
ANi-Strm插件在市场里找不到！
地址我也加入进去了。
![123](https://github.com/honue/MoviePilot-Plugins/assets/167842055/3d8aa759-663d-4b18-a1ed-f5c68eb218b1)
![333](https://github.com/honue/MoviePilot-Plugins/assets/167842055/d214adc4-29aa-4d5f-b133-2dfa9ca64a25)
代理也弄好了，就是不显示ANi-Strm插件

**Comment by honue** [comment]
插件地址填错了，代理变量也错了
