### ISSUE TITLE
Ani-strm 插件市场没有，有其他几个！

### ISSUE THREAD

**Issue by Awhitedressy** [honue/MoviePilot-Plugins#25]
错的地方已经改好，也可以搜到插件，就是能搜到4个，其他没有~！

[
![123](https://github.com/honue/MoviePilot-Plugins/assets/167842055/ab9f5ab9-676c-40a3-9d94-0194d72abc17)
![144](https://github.com/honue/MoviePilot-Plugins/assets/167842055/5afa0649-739f-4f9f-ad62-de33d207d3e5)
![344](https://github.com/honue/MoviePilot-Plugins/assets/167842055/e88bdb3f-8750-4deb-85ef-ece2bd83c741)
](url)

地址不能加 最后不能加“/” 加了就搜不到插件！

**Comment by honue** [comment]
升级mp版本1.7版本bug 最多100个插件

**Comment by Awhitedressy** [comment]
![33444](https://github.com/honue/MoviePilot-Plugins/assets/167842055/cecee599-9234-46ab-a5d8-3060086564a7)

我这个是最新版本，推荐用哪个版本？？
