### ISSUE TITLE
捷径下载的最后一步缺少key参数

### ISSUE THREAD

**Issue by AisukaYuki** [honue/MoviePilot-Plugins#28]
![IMG_4423](https://github.com/honue/MoviePilot-Plugins/assets/17586327/85974257-e538-423f-8380-c5b866b90c56)
箭头处缺少key词典

**Comment by honue** [comment]
ok 回头我改下

**Comment by honue** [comment]
fixed in ea4ede41bccc6bfcee1a3207da3b6a0092e23954
