### ISSUE TITLE
自适应IntroSkip  一直报错

### ISSUE THREAD

**Issue by dwwl886** [honue/MoviePilot-Plugins#31]
【ERROR】2024-05-19 09:33:23,729 - SkipHelper.py - 异常错误：Expecting value: line 1 column 1 (char 0)

版本是1.6

**Comment by honue** [comment]
重置插件

**Comment by dwwl886** [comment]
这个插件不支持 电影吗    我测试电视剧 没有问题

**Comment by honue** [comment]
> 这个插件不支持 电影吗 我测试电视剧 没有问题

电影没必要用这个插件
