### ISSUE TITLE
豆瓣书影音档案 无反应

### ISSUE THREAD

**Issue by zww94** [honue/MoviePilot-Plugins#33]
填写了cookie ，然后日志一片空白

**Comment by honue** [comment]
检查webhook

**Comment by 474564104** [comment]
大佬，我这也是一样的问题，webhook测试了一下，好像没问题，如图，我的TG是@panda7758258   希望能够寻得帮助谢谢

jellyfin配置

![Image](https://github.com/user-attachments/assets/9bed04e9-bf9e-4ded-9e5a-fbaf75a1ddc4)

![Image](https://github.com/user-attachments/assets/fd672fb9-f520-47ef-8ef6-fcc2eab13253)

播放时在系统上看日志能看到有回调过来

![Image](https://github.com/user-attachments/assets/ee975e6c-8f07-43fc-9874-625dcc2ca4b3)

插件配置

![Image](https://github.com/user-attachments/assets/5616e581-9a21-487e-9929-fb162b539bca)

日志一片空白

![Image](https://github.com/user-attachments/assets/810cd2df-5edb-4e82-885a-6dd01a66c19e)

测试请求webhook接口地址正常
![Image](https://github.com/user-attachments/assets/97470cec-6b0c-48a8-84f2-791154dc3679)
