### ISSUE TITLE
豆瓣书影音档案插件使用问题

### ISSUE THREAD

**Issue by 99Mr-Z** [honue/MoviePilot-Plugins#35]
目前插件cookie留空使用自动同步cookie，似乎不生效，无法通过cookiecloud进行豆瓣同步，通过手动在控制台添加cookie能够正常使用。

一个其他提议，能否将留空同步改为一个开关选项

开启则使用cookiecloud，下方输入框则改为不可输入（同时再添加一个子项，立即获取一次豆瓣cookie，自动填充到cookie信息中，以便知道cookie信息的确同步到插件中）

不开启则使用自己输入的cookie，下方输入框允许输入cookie信息。
![image](https://github.com/honue/MoviePilot-Plugins/assets/117721493/04153281-f324-4351-85fa-d5750a1576ba)

**Comment by honue** [comment]
问题不在cookie有没有的问题，问题在于cookie中是否有ck这个键值，你不填保活这个会在后续的cookie同步中丢失。建议使用固定cookie目前已经有效使用一个月了。

**Comment by 99Mr-Z** [comment]
> 问题不在cookie有没有的问题，问题在于cookie中是否有ck这个键值，你不填保活这个会在后续的cookie同步中丢失。建议使用固定cookie目前已经有效使用一个月了。

cookie保活在chrome插件里设定了，间隔时间是一小时，另外提议可否进行采纳？

**Comment by honue** [comment]
> > 问题不在cookie有没有的问题，问题在于cookie中是否有ck这个键值，你不填保活这个会在后续的cookie同步中丢失。建议使用固定cookie目前已经有效使用一个月了。
> 
> cookie保活在chrome插件里设定了，如何设定固定cookie？，另外提议可否进行采纳？

根本就实现不了，你看哪个插件里用了js

**Comment by 99Mr-Z** [comment]
> > > 问题不在cookie有没有的问题，问题在于cookie中是否有ck这个键值，你不填保活这个会在后续的cookie同步中丢失。建议使用固定cookie目前已经有效使用一个月了。
> > 
> > 
> > cookie保活在chrome插件里设定了，如何设定固定cookie？，另外提议可否进行采纳？
> 
> 根本就实现不了，你看哪个插件里用了js

不好意思，并不清楚实际如何实现的，只是理想化的一个提议，抱歉

**Comment by honue** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/03878991-ca29-4ea5-af3a-2fc933257672)

**Comment by 99Mr-Z** [comment]
> ![image](https://private-user-images.githubusercontent.com/57806936/333804220-03878991-ca29-4ea5-af3a-2fc933257672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDUwMTYsIm5iZiI6MTcxNjY0NDcxNiwicGF0aCI6Ii81NzgwNjkzNi8zMzM4MDQyMjAtMDM4Nzg5OTEtY2EyOS00ZWE1LWFmM2EtMmZjOTMzMjU3NjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEzNDUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzQ2NzhhMzU5MWFmNzk1NDcyMDNiODQxODdkNDBkMjU3MTllZTcxNWEwMGE5OWIxMDFlYWI5MGVhN2Q1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nA0hjlpHmr-f6DttgGLQf93wy_2cOjtMLH_YS2xKCcE)

![image](https://github.com/honue/MoviePilot-Plugins/assets/117721493/e0fec3c2-4d60-4697-a0e6-52481a71ab2d)

**Comment by 99Mr-Z** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/117721493/4209d662-d013-4bc8-8fad-3432c80a0af7)
从日志信息里看到留空后每次进行同步，似乎并没有生效，在豆瓣看过的记录里也未更新观看记录

**Comment by 99Mr-Z** [comment]
留空后需要手动同步一次CC来保证MP能够读取到豆瓣的cookie信息，谢谢说明和回复，已经了解了插件的使用方式和注意事项了
