### ISSUE TITLE
豆瓣书影音档案设置“媒体路径排除关键词”异常

### ISSUE THREAD

**Issue by loongcheung** [honue/MoviePilot-Plugins#36]
媒体库是 PLEX，不设置 “媒体路径排除关键词” 可以正常同步。麻烦大佬有空瞅瞅：
<img width="1215" alt="image" src="https://github.com/honue/MoviePilot-Plugins/assets/25630765/d8d7084d-fa38-455b-8d5c-b4f3f6d034ef">

**Comment by honue** [comment]
贴上你设置的关键词，以及你的媒体路径，不然我只能给你算一卦了。

**Comment by loongcheung** [comment]
插件排除关键词：audiobooks
媒体路径：/data/audiobooks

**Comment by honue** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/9fed1a13-c9ef-4e77-9437-d31b57324f4e)
测试正常

**Comment by loongcheung** [comment]
<img width="715" alt="image" src="https://github.com/user-attachments/assets/fa863c28-3cfb-4ea0-8097-1c4c008b049a">
这个问题发现是 Plex 的 webhook 没有 path

**Comment by loongcheung** [comment]
这个问题我调试了下 是 Plex 的 webhook 没有 返回 path。屏蔽词对 Plex 就报错了

**Comment by honue** [comment]
那估计得完善下主程序了，我这边先改下，对None path 不做过滤

**Comment by honue** [comment]
> 这个问题我调试了下 是 Plex 的 webhook 没有 返回 path。屏蔽词对 Plex 就报错了

你这个问题要从源头解决，只能去改mp主程序的webhook，我没plex调试不了。我插件这先对None path 不做过滤操作。

**Comment by ptninja** [comment]
遇到类似问题，想排除掉音乐，否则会匹配到奇怪的条目，比如

```
【INFO】2024-10-16 15:52:23,467 - doubanwatching - 王妃 (None) 同步到档案成功
【INFO】2024-10-16 15:52:22,146 - doubanwatching - 查询：王妃 (None) => 匹配豆瓣：摩纳哥王妃 https://movie.douban.com/subject/10450713/
【INFO】2024-10-16 15:52:18,069 - doubanwatching - 开始尝试获取 王妃 (None) 豆瓣id
【INFO】2024-10-16 15:52:18,068 - themoviedb - 王妃 TMDB识别结果：电影 None (2015) 518061
【INFO】2024-10-16 15:52:18,054 - themoviedb - 正在识别 None ...
【INFO】2024-10-16 15:52:10,497 - themoviedb - 正在识别 王妃 ...
【INFO】2024-10-16 15:52:10,490 - doubanwatching - 开始播放 王妃 (None)
【WARNING】2024-10-16 15:52:10,490 - doubanwatching - 媒体路径为空,不执行过滤操作
```
