### ISSUE TITLE
插件日志清理问题

### ISSUE THREAD

**Issue by Enderiose** [honue/MoviePilot-Plugins#37]
插件日志清理-删除插件日志列表为：No data available
应该怎么设置才能看到插件列表

**Comment by honue** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/e90a4637-cfa4-4fc4-9d94-832893665f99)
我这正常

**Comment by honue** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/7d485538-4223-4404-acd7-98d84e38c918)
看看是不是你的网络问题，这部分要能获取插件市场的插件。

**Comment by Enderiose** [comment]
代理服务器是部署了的，就是不知道是不是跟主程序配置文件的github_token有关系，不知道从哪获取就删除了这个环境变量，空值不能下插件市场的插件，删除就可以下了

**Comment by honue** [comment]
> 代理服务器是部署了的，就是不知道是不是跟主程序配置文件的github_token有关系，不知道从哪获取就删除了这个环境变量，空值不能下插件市场的插件，删除就可以下了

https://github.com/settings/tokens 
这 generate a new key (classic)

**Comment by Enderiose** [comment]
谢谢，回复真快🙏

**Comment by honue** [comment]
> 谢谢，回复真快🙏

thanks for your star😄
