### ISSUE TITLE
豆瓣书影音档案插件webhook相关设置说明

### ISSUE THREAD

**Issue by s0urcelab** [honue/MoviePilot-Plugins#38]
插件说明里提到需要媒体库开启webhook，但没有说清楚webhook的发送地址应该指向哪儿，还有具体的消息体需要遵循什么结构
（emby，plex，jellyfin这3个媒体库默认的消息体应该有区别）

**Comment by zww94** [comment]
同问

**Comment by honue** [comment]
mp做了模块化，这块无需你们操心，只需要打开webhook，播放事件能够通知到mp就行

**Comment by honue** [comment]
https://t.me/moviepilot_official
