### ISSUE TITLE
豆瓣书影音档案 仪表盘组件怎么使用

### ISSUE THREAD

**Issue by 7-orion** [honue/MoviePilot-Plugins#39]
才发现有更新，刚更新了新版本，但是仪表盘里找不到相关组件，已重置了插件。

![PixPin_2024-06-11_11-35-55](https://github.com/honue/MoviePilot-Plugins/assets/32628296/fb749dd8-5ee3-4753-8dcb-87373cb600c6)

**Comment by honue** [comment]
要启用插件才会显示

**Comment by 7-orion** [comment]
> 要启用插件才会显示

已经启用了的 关闭重开过插件 整个mp也重启过
![PixPin_2024-06-11_11-35-55](https://github.com/honue/MoviePilot-Plugins/assets/32628296/c2e5edfe-7dbe-4c94-aee9-85ccbfa6e3e5)

**Comment by honue** [comment]
![IMG_0689](https://github.com/honue/MoviePilot-Plugins/assets/57806936/62e30aa4-fdcc-4e61-9b0a-8678c2d0a52b)
不知道我这正常

**Comment by 7-orion** [comment]
> ![IMG_0689](https://private-user-images.githubusercontent.com/57806936/338454090-62e30aa4-fdcc-4e61-9b0a-8678c2d0a52b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODU5MjEsIm5iZiI6MTcxODA4NTYyMSwicGF0aCI6Ii81NzgwNjkzNi8zMzg0NTQwOTAtNjJlMzBhYTQtZmRjYy00ZTYxLTliMGEtODY3OGMyZDBhNTJiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNjAwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTVmNjFlODBjZjM0NWJiZWYyNGNkMDBmZDcyMjMwZDVhZjIzY2E1OTFiYWU2OGRiZmIxZTY2MDdjMDQyMmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.grIX9mHMVK3_Nxmf2LTkABoKmaq5ZXMIQUFwk-FBKCc) 不知道我这正常

我试装了下每日一言的插件，是能正常在仪表盘里出现的…我打算完整的卸载重装豆瓣书影音这个插件，但是使用“插件彻底卸载”插件来卸载后重装，原来填的内容还有日志都还在…不知道该如何操作 大佬可以指点一下吗？（我看了下我安装的这个豆瓣插件图标还是原来绿底的那个，卸载后在商店里是白底的，不知道是不是有问题）。在mp的群里问了没人回…

**Comment by honue** [comment]
重装日志不会删除，这个是正常的。

**Comment by honue** [comment]
tg留一下 帮你远程看看

**Comment by 7-orion** [comment]
> tg留一下 帮你远程看看

谢谢 晚上联系您可以嘛 现在在单位不太好操作

**Comment by honue** [comment]
ok

**Comment by 7-orion** [comment]
已经自己搞定了 谢谢大佬 大佬可以考虑下增加一个小于x分钟不不标记的功能嘛 不然感觉容易随手打开一个电影就标记已看了

**Comment by honue** [comment]
> 已经自己搞定了 谢谢大佬 大佬可以考虑下增加一个小于x分钟不不标记的功能嘛 不然感觉容易随手打开一个电影就标记已看了

自己排查出了什么问题？怎么解决的
