### ISSUE TITLE
ANiStrm的链接无法在jellyfin里播放

### ISSUE THREAD

**Issue by LoSiTeE** [honue/MoviePilot-Plugins#4]
尝试过用代理，不用代理均不可播放。比较离谱的是，如果我打开主路由的IPV6，播放就正常了。请问是否IPV4无法访问该网站？

**Comment by LoSiTeE** [comment]
<html>
<body>
<h2 style="text-align: center; color: rgb(0, 0, 0); font-family: &quot;Lucida Console&quot;, Consola, Monaco, monospace, &quot;Courier New&quot;, Courier, serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">nyanmisaka-jellyfin1</h2>
date | stream | content
-- | -- | --
2024/01/04 16:21:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:21:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m11[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mExecuteQueuedTasks[39;49m
2024/01/04 16:21:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:21:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m11[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m[39;49m[37m [39;49m[39;49m[32mCompleted[39;49m[39;49m[37m after [39;49m[39;49m[35m0[39;49m[39;49m[37m minute(s) and [39;49m[39;49m[35m0[39;49m[39;49m[37m seconds[39;49m
2024/01/04 16:21:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:21:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m11[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mExecuting [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m
2024/01/04 16:21:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:21:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m11[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mQueuing task [39;49m[39;49m[36mItemAddedScheduledTask[39;49m
2024/01/04 16:21:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:21:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m11[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[36mIntervalTrigger[39;49m[39;49m[37m fired for task: [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m
2024/01/04 16:20:49 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:49[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mExecuteQueuedTasks[39;49m
2024/01/04 16:20:49 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:49[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m[39;49m[37m [39;49m[39;49m[32mCompleted[39;49m[39;49m[37m after [39;49m[39;49m[35m0[39;49m[39;49m[37m minute(s) and [39;49m[39;49m[35m0[39;49m[39;49m[37m seconds[39;49m
2024/01/04 16:20:49 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:49[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mExecuting [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m
2024/01/04 16:20:49 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:49[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mQueuing task [39;49m[39;49m[36mItemAddedScheduledTask[39;49m
2024/01/04 16:20:49 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:49[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[36mIntervalTrigger[39;49m[39;49m[37m fired for task: [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m
2024/01/04 16:20:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mExecuteQueuedTasks[39;49m
2024/01/04 16:20:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m[39;49m[37m [39;49m[39;49m[32mCompleted[39;49m[39;49m[37m after [39;49m[39;49m[35m0[39;49m[39;49m[37m minute(s) and [39;49m[39;49m[35m0[39;49m[39;49m[37m seconds[39;49m
2024/01/04 16:20:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m3[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mExecuting [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m
2024/01/04 16:20:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m10[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[37mQueuing task [39;49m[39;49m[36mItemAddedScheduledTask[39;49m
2024/01/04 16:20:19 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:19[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m10[39;49m[39;49m[30m] [39;49m[39;49m[37mEmby.Server.Implementations.ScheduledTasks.TaskManager[39;49m[39;49m[30m: [39;49m[39;49m[36mIntervalTrigger[39;49m[39;49m[37m fired for task: [39;49m[39;49m[36mWebhook Item Added Notifier[39;49m
2024/01/04 16:20:14 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:14[39;49m[39;49m[30m] [[39;49m[39;49m[33mWRN[39;49m[39;49m[30m] [[39;49m[39;49m[37m22[39;49m[39;49m[30m] [39;49m[39;49m[37mJellyfin.Server.Middleware.ResponseTimeMiddleware[39;49m[39;49m[30m: [39;49m[39;49m[37mSlow HTTP Response from [39;49m[39;49m[36mhttp://192.168.86.4:8096/Items/66e88baf0d076fc37437a36e71b52d20/PlaybackInfo?UserId=c07f6e66c5984cfe905b7af7e144fd48&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000[39;49m[39;49m[37m to [39;49m[39;49m[36m192.168.86.5[39;49m[39;49m[37m in [39;49m[39;49m[32m0:00:07.6658896[39;49m[39;49m[37m with Status Code [39;49m[39;49m[35m200[39;49m
2024/01/04 16:20:14 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:14[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m22[39;49m[39;49m[30m] [39;49m[39;49m[37mJellyfin.Api.Helpers.MediaInfoHelper[39;49m[39;49m[30m: [39;49m[39;49m[37mStreamBuilder.BuildVideoItem( Profile=[39;49m[39;49m[36mAnonymous Profile[39;49m[39;49m[37m, Path=[39;49m[39;49m[36mhttps://resources.ani.rip/2023-10/[ANi] Overtake! - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4?d=true[39;49m[39;49m[37m, AudioStreamIndex=[39;49m[39;49m[34mnull[39;49m[39;49m[37m, SubtitleStreamIndex=[39;49m[39;49m[34mnull[39;49m[39;49m[37m ) => ( PlayMethod=[39;49m[39;49m[32mDirectPlay[39;49m[39;49m[37m, TranscodeReason=[39;49m[39;49m[32m0[39;49m[39;49m[37m ) [39;49m[39;49m[36mmedia:/videos/66e88baf-0d07-6fc3-7437-a36e71b52d20/stream.mp4?MediaSourceId=66e88baf0d076fc37437a36e71b52d20&Static=true&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&api_key=<token>&Tag=822b284d9a08314f3a7bd89387899d5e[39;49m
2024/01/04 16:20:14 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:14[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m22[39;49m[39;49m[30m] [39;49m[39;49m[37mJellyfin.Api.Helpers.MediaInfoHelper[39;49m[39;49m[30m: [39;49m[39;49m[37mUser policy for [39;49m[39;49m[36mszjawo[39;49m[39;49m[37m. EnablePlaybackRemuxing: [39;49m[39;49m[34mTrue[39;49m[39;49m[37m EnableVideoPlaybackTranscoding: [39;49m[39;49m[34mTrue[39;49m[39;49m[37m EnableAudioPlaybackTranscoding: [39;49m[39;49m[34mTrue[39;49m
2024/01/04 16:20:13 | stdout | [39;49m[37m   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)[39;49m
2024/01/04 16:20:13 | stdout | [39;49m[37m   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)[39;49m
2024/01/04 16:20:13 | stdout | [39;49m[37m   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)[39;49m
2024/01/04 16:20:13 | stdout | [39;49m[37m   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)[39;49m
2024/01/04 16:20:13 | stdout | [39;49m[37mMediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.[39;49m
2024/01/04 16:20:13 | stdout | [0m[?1h=[39;49m[30m[[39;49m[39;49m[37m08:20:13[39;49m[39;49m[30m] [[39;49m[39;49m[37m[39;49m[37m[41mERR[39;49m[39;49m[30m] [[39;49m[39;49m[37m22[39;49m[39;49m[30m] [39;49m[39;49m[37mMediaBrowser.Providers.TV.EpisodeMetadataService[39;49m[39;49m[30m: [39;49m[39;49m[37mError in [39;49m[39;49m[36mffprobe[39;49m
2024/01/04 16:20:13 | stdout | [0m[1;31mhttps://resources.ani.rip/2023-10/[ANi] Overtake! - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4?d=true: End of file
2024/01/04 16:20:13 | stdout | [0m[0;39m[tls @ 0x5610cf7ac900] [0m[1;31mIO error: End of file
2024/01/04 16:20:13 | stdout | [0;39m[tls @ 0x5610cf7ac900] [0m[1;31mError in the pull function.
2024/01/04 16:20:07 | stdout | [39;49m[30m[[39;49m[39;49m[37m08:20:07[39;49m[39;49m[30m] [[39;49m[39;49m[37mINF[39;49m[39;49m[30m] [[39;49m[39;49m[37m10[39;49m[39;49m[30m] [39;49m[39;49m[37mMediaBrowser.MediaEncoding.Encoder.MediaEncoder[39;49m[39;49m[30m: [39;49m[39;49m[36m/usr/lib/jellyfin-ffmpeg/ffprobe[39;49m[39;49m[37m [39;49m[39;49m[36m-analyzeduration 200M -i "https://resources.ani.rip/2023-10/[ANi] Overtake! - 01 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4?d=true" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format[39;49m


</body>
</html>

**Comment by honue** [comment]
格式贴的太乱了

**Comment by honue** [comment]
不用代理不可播放是正常现象，ani open服务器基于cf+dg，后面v4 v6原因自己排查

**Comment by honue** [comment]
readme说的很清楚了，要使用代理，没问题我关了

**Comment by LoSiTeE** [comment]
> 不用代理不可播放是正常现象，ani open服务器基于cf+dg，后面v4 v6原因自己排查

回复的好快……我是用代理也放不了，不用也放不了……只有开了ipv6才能放

**Comment by LoSiTeE** [comment]
> readme说的很清楚了，要使用代理，没问题我关了

行吧，我自己再看看

**Comment by honue** [comment]
自己排除吧，我这边都一切正常，可能对梯子ip有一定要求，我关了

**Comment by LoSiTeE** [comment]
> 自己排除吧，我这边都一切正常，可能对梯子ip有一定要求，我关了

老哥，我试过了，我这边用open.ani.rip正常播放，但是用resources.ani.rip就死活不好使……有什么解决办法吗？或者插件里加个选项，可以自行选择播放源链接

**Comment by honue** [comment]
检查resources.ani.rip是否走代理规则

**Comment by LoSiTeE** [comment]
> 检查resources.ani.rip是否走代理规则

神奇……好了居然
