### ISSUE TITLE
IntroSkip插件设置后以后无法标记片头时间，只能标记到片尾时间

### ISSUE THREAD

**Issue by saarjoye** [honue/MoviePilot-Plugins#41]
![Uploading 微信图片_20240617120756.png…]()

**Comment by honue** [comment]
图片裂了，没发出来，我这正常。

**Comment by saarjoye** [comment]
【INFO】2024-06-17 12:23:59,702 - adaptiveintroskip - 墨雨云间 没有设置过片头片尾信息，跳过
【INFO】2024-06-17 12:23:59,600 - adaptiveintroskip -  
【INFO】2024-06-17 12:22:38,797 - adaptiveintroskip - 晓朝夕 没有设置过片头片尾信息，跳过
【INFO】2024-06-17 12:22:38,759 - adaptiveintroskip -  
【INFO】2024-06-17 12:17:52,663 - adaptiveintroskip - 战火中的青春 没有设置过片头片尾信息，跳过
【INFO】2024-06-17 12:17:52,580 - adaptiveintroskip -  
【INFO】2024-06-17 12:00:07,025 - adaptiveintroskip -  
【INFO】2024-06-17 12:00:02,203 - adaptiveintroskip -  
【INFO】2024-06-17 11:59:01,958 - adaptiveintroskip -  
【INFO】2024-06-17 11:59:01,906 - adaptiveintroskip -  
【INFO】2024-06-17 11:57:04,066 - adaptiveintroskip - 凡人修仙传 S1E99 星海飞驰23 后续剧集片尾设置在 19分38秒 开始
【INFO】2024-06-17 11:57:02,306 - adaptiveintroskip -  
【INFO】2024-06-17 11:57:02,298 - adaptiveintroskip - 凡人修仙传 S1E99 星海飞驰23 后续剧集片尾设置在 19分38秒 开始
【INFO】2024-06-17 11:57:01,965 - adaptiveintroskip -  
【INFO】2024-06-17 11:56:00,919 - adaptiveintroskip -  
【INFO】2024-06-17 11:56:00,846 - adaptiveintroskip -  
【INFO】2024-06-17 11:54:12,987 - adaptiveintroskip -  
【INFO】2024-06-17 11:54:12,852 - adaptiveintroskip -  
【INFO】2024-06-17 11:53:11,808 - adaptiveintroskip -  
【INFO】2024-06-17 11:53:11,722 - adaptiveintroskip -  
【INFO】2024-06-17 11:50:34,874 - adaptiveintroskip -  
【INFO】2024-06-17 11:49:33,642 - adaptiveintroskip -  
【INFO】2024-06-17 11:41:34,334 - adaptiveintroskip -  
【INFO】2024-06-17 11:40:33,275 - adaptiveintroskip -  
【INFO】2024-06-17 11:38:59,468 - adaptiveintroskip -  
【INFO】2024-06-17 11:38:58,387 - adaptiveintroskip -  
【INFO】2024-06-17 11:37:58,394 - adaptiveintroskip -  
【INFO】2024-06-17 11:35:21,551 - adaptiveintroskip -  
【INFO】2024-06-17 11:34:21,453 - adaptiveintroskip -  
【INFO】2024-06-17 11:33:30,084 - adaptiveintroskip - 凡人修仙传 S1E98 星海飞驰22 后续剧集片尾设置在 19分16秒 开始
【INFO】2024-06-17 11:33:29,577 - adaptiveintroskip -  
【INFO】2024-06-17 11:32:29,538 - adaptiveintroskip -  
【INFO】2024-06-17 11:30:51,432 - adaptiveintroskip -  
【INFO】2024-06-17 11:30:11,759 - adaptiveintroskip - 战火中的青春 没有设置过片头片尾信息，跳过
【INFO】2024-06-17 11:30:11,743 - adaptiveintroskip -  
【INFO】2024-06-17 11:29:51,188 - adaptiveintroskip -  
【INFO】2024-06-17 11:26:51,147 - adaptiveintroskip - 你好，星期六 S3E22 20240615期：戚薇回应“野心写在脸上” 目前不在设置的时间段内，不标记片头片尾
【INFO】2024-06-17 11:26:51,133 - adaptiveintroskip -  
【INFO】2024-06-17 11:22:19,703 - adaptiveintroskip - 你好，星期六 S3E22 20240615期：戚薇回应“野心写在脸上” 目前不在设置的时间段内，不标记片头片尾
【INFO】2024-06-17 11:22:19,657 - adaptiveintroskip -  
【INFO】2024-06-17 11:16:32,065 - adaptiveintroskip - 斗罗大陆Ⅱ绝世唐门 S1E53 第 53 集 后续剧集片尾设置在 19分29秒 开始


看日志，只有片尾成功标记到了。片头一直没办法标记。有时返回的是空的值。不知道什么原因

**Comment by honue** [comment]
片头要手动暂停一下才能标记

**Comment by saarjoye** [comment]
我手动调到片头结束位置。然后点暂停在播放。但是好像不生效。

**Comment by honue** [comment]
看看是不是webhook没选暂停事件

**Comment by saarjoye** [comment]
emby里的webhook里选了播放的4个事件，mp里服务通知里只有播放和停止，没有暂停

**Comment by honue** [comment]
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/29694706-8d9f-4862-bb5f-5326f2bd9727)
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/1211f06a-04cc-4792-8152-20cebe8d5657)
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/46985beb-d53b-47fb-965e-08609a9489af)
无法重新问题。

**Comment by saarjoye** [comment]
只要暂停就好吗？还是说需要暂停后在播放

**Comment by honue** [comment]
暂停后播放

**Comment by saarjoye** [comment]
【ERROR】2024-06-17 20:17:48,529 - skip_helper.py - 异常错误：'RunTimeTicks'
在apple tv上的infuse播放，一直提示这个错误

**Comment by honue** [comment]
哦，你原来不是emby客户端啊。

> 在片头限定时间内，暂停一下恢复播放能够将后续剧集的片头跳转全标记在这个点，在片尾限定时间内，片尾正常退出播放能够将后续剧集的片尾开始全标记在这个点，如有问题欢迎交流。
目前回报暂停信息的只有emby官方的客户端(包括小秘)、网页端，所以只推荐这几个客户端的用户使用。

**Comment by saarjoye** [comment]
啊。尴尬。infuse里使用的emby库也不行吗？

**Comment by honue** [comment]
不行，infuse不会回报暂停信息，fileball同样

**Comment by saarjoye** [comment]
好像我在conflux播放器的时候可以标记片尾，断标不上版头，我以为infuse可以。现在明白了，谢谢大佬
