### ISSUE TITLE
共享识别词插件自动运行时总是获取失败，手动才能成功

### ISSUE THREAD

**Issue by ZACKLZ** [honue/MoviePilot-Plugins#43]
![image](https://github.com/honue/MoviePilot-Plugins/assets/82872715/d69c782a-b4f2-4a33-ab07-8e2ddf0f7437)
![image](https://github.com/honue/MoviePilot-Plugins/assets/82872715/9f10714d-5e48-494f-ab87-e9850081ebea)

如上图当收到失败通知后，尝试手动就能成功

**Comment by honue** [comment]
https://github.com/honue/MoviePilot-Plugins/issues/32#issuecomment-2160331069

**Comment by ZACKLZ** [comment]
是要更新地址就行了是么
