### ISSUE TITLE
Tracker替换插件可以支持多个站点吗?

### ISSUE THREAD

**Issue by paysenyu** [honue/MoviePilot-Plugins#47]
目前的插件我设置了下好像只能单个词组替换, 比如 A.COM 替换成B.COM

但是我想实现, A =>B 同时 C=> D

不知道是否可以更新,感谢大大

**Comment by honue** [comment]
这个插件推到主仓库了，我回头看看。

**Comment by paysenyu** [comment]
> 这个插件推到主仓库了，我回头看看。

非常感谢
