### ISSUE TITLE
AniStrm无法创建strm源文件

### ISSUE THREAD

**Issue by Akimio521** [honue/MoviePilot-Plugins#5]
报错日志如下
![image](https://github.com/honue/MoviePilot-Plugins/assets/77880495/1e7d2cf4-f8d2-427f-8ba5-f5d193c4d6a5)

**Comment by honue** [comment]
填的路径不存在

**Comment by Akimio521** [comment]
我原本只挂载了/media/下载，原来不会创建后面的目录
