### ISSUE TITLE
请问一下，新增剧集，可以按照之前的自动标注吗

### ISSUE THREAD

**Issue by lifujie25** [honue/MoviePilot-Plugins#50]
请问一下，新增剧集，可以按照之前的自动标注吗

**Comment by honue** [comment]
可以

**Comment by lifujie25** [comment]
我的新增的没有自动标记，是不是有哪里没设置啊
![Uploading WechatIMG3813.jpg…]()

**Comment by lifujie25** [comment]
![WechatIMG3813](https://github.com/user-attachments/assets/346248ed-ec63-42da-85fe-597889035a69)

**Comment by lifujie25** [comment]
大佬，空的时候帮忙看看是不是还需要设置哪里，后续更新的才会标记

**Comment by lifujie25** [comment]
<img width="963" alt="image" src="https://github.com/user-attachments/assets/810e2874-0b25-452e-9a02-073c79337b44">
<img width="851" alt="image" src="https://github.com/user-attachments/assets/a7910ea4-e00a-4d42-99b6-95bc66c3b426">

**Comment by honue** [comment]
![image](https://github.com/user-attachments/assets/5c82cad4-05f5-4780-adb9-7072561e8254)
看日志，之前标注过，之后的新剧集可以按照存在的信息标注。
