### ISSUE TITLE
ani 似乎改了域名

### ISSUE THREAD

**Issue by kai456789** [honue/MoviePilot-Plugins#58]
原 https://aniopen.an-i.workers.dev 出現 page not found
![image](https://github.com/user-attachments/assets/1c8ef64c-9083-4cc6-bb62-497939f98845)

https://openani.an-i.workers.dev/  這個可用

**Comment by Cijanx** [comment]
是的，同一个问题，原链接生成的strm都不能播放，测试了下链接，是挂掉了

**Comment by ddlanlan** [comment]
> 是的，同一个问题，原链接生成的strm都不能播放，测试了下链接，是挂掉了

这个是怎么修改一下呢？

**Comment by honue** [comment]
做了个替换

**Comment by kai456789** [comment]
> 做了個替換

感謝修正 已更新到2.4版本 發現strm裡還是用aniopen.an-i.workers.dev 無法播放

[新网球王子 U-17世界杯篇 - S02E02 - 第 2 集.strm.txt](https://github.com/user-attachments/files/17320975/U-17.-.S02E02.-.2.strm.txt)

[https://aniopen.an-i.workers.dev/2024-10/%5BANi%5D%20%E6%96%B0%E7%B6%B2%E7%90%83%E7%8E%8B%E5%AD%90%20U-17%20%E4%B8%96%E7%95%8C%E7%9B%83%20SEMIFINAL%20-%2002%20%5B1080P%5D%5BBaha%5D%5BWEB-DL%5D%5BAAC%20AVC%5D%5BCHT%5D.mp4?d=true](url)

**Comment by 7-orion** [comment]
> > 做了個替換
> 
> 感谢已更新到2.4版本修改发现strm里还是用aniopen.an-i.workers.dev无法播放
> 
> [新网球王子 U-17 世界杯篇 - S02E02 - 第 2 集.strm.txt](https://github.com/user-attachments/files/17320975/U-17.-.S02E02.-.2.strm.txt)
> 
> [https://aniopen.an-i.workers.dev/2024-10/%5BANi%5D%20%E6%96%B0%E7%B6%B2%E7%90%83%E7%8E%8B%E5 %AD%90%20U-17%20%E4%B8%96%E7%95%8C%E7%9B%83%20SEMIFINAL%20-%2002%20%5B1080P%5D%5BBaha%5D%5BWEB-DL% 5D%5BAAC%20AVC%5D%5BCHT%5D.mp4?d=true](url)

+1 同样的问题

**Comment by Cijanx** [comment]
> 做了个替换

前几天的可以，今天的又变回来了

https://aniopen.an-i.workers.dev/2024-10/%5BANi%5D%20%E6%A9%9F%E6%A2%B0%E8%87%82%20-%2002%20%5B1080P%5D%5BBaha%5D%5BWEB-DL%5D%5BAAC%20AVC%5D%5BCHT%5D.mp4?d=true

**Comment by kai456789** [comment]
等作者修正 暫時用這大佬版本 掛cron 定時 
https://github.com/Kaery40/Ani-strm

**Comment by honue** [comment]
我没细看 sry. 最近实在有点忙，等会我看看...

**Comment by honue** [comment]
ok 上次有个地方忘了改。

**Comment by kai456789** [comment]
> ok 上次有個地方忘了改。

2.41 經測試已可用 感謝大佬

**Comment by wintsa123** [comment]
2.4.2不行了
