### ISSUE TITLE
AniStrm使用EMBY播放，显示没有兼容的流是什么原因？

### ISSUE THREAD

**Issue by tornadomord** [honue/MoviePilot-Plugins#6]
如题，麻烦了

**Comment by honue** [comment]
代理问题

**Comment by tornadomord** [comment]
> 代理问题，具体看readme

按readme给emby添加了环境变量，还是这个问题，其他非anistrm添加的strm也播放不了了，小白，大神费心了

**Comment by honue** [comment]
emby容器与代理之间的网络联通性问题

**Comment by yating1022** [comment]
我是网页中显示不兼容的流，客户端正常

**Comment by honue** [comment]
> 我是网页中显示不兼容的流，客户端正常

网络问题 建议自己看看emby的日志
