### ISSUE TITLE
ANiStrm插件的RSS订阅貌似没更新了

### ISSUE THREAD

**Issue by shiji5824666** [honue/MoviePilot-Plugins#63]
ANiStrm插件的RSS订阅貌似没更新了
RSS链接： https://api.ani.rip/ani-download.xml 

![Snipaste_2024-10-19_11-25-28](https://github.com/user-attachments/assets/1b532f19-b835-4900-b31a-e4f5c11cd9f9)

**Comment by kai456789** [comment]
+1 19號開始 

【WARNING】2024-10-20 00:20:43,232 - anistrm - 未獲取到檔案資訊，3秒後重試 ...
【WARNING】2024-10-20 00:20:20,168 - anistrm - 未獲取到檔案資訊，3秒後重試 ...
【INFO】2024-10-20 00:00:00,297 - anistrm - 本次處理 36 個檔案
【INFO】2024-10-19 23:40:00,411 - anistrm - 本次處理 36 個檔案
【INFO】2024-10-19 23:20:00,264 - anistrm - 本次處理 34 個檔案
【INFO】2024-10-19 23:00:00,284 - anistrm - 本次處理 33 個檔案
【INFO】2024-10-19 22:40:00,402 - anistrm - 本次處理 33 個檔案
【INFO】2024-10-19 22:20:23,405 - anistrm - 本次處理 33 個檔案
【WARNING】2024-10-19 22:20:20,140 - anistrm - 未獲取到檔案資訊，3秒後重試 ...

**Comment by honue** [comment]
我不知道是不是open-ani 那边特意暂停更新了。可能是咱的流量太大了，我不确定人家是不是不欢迎我们串流使用。

**Comment by honue** [comment]
![image](https://github.com/user-attachments/assets/12d3fb1e-520d-4fae-8b98-1a358bf289e0)

**Comment by honue** [comment]
这是我于23.11.25日与open ani的沟通邮件。

**Comment by kai456789** [comment]
> 这是我于2023.11.25与open-ani的沟通邮件。我估计是平台作者不欢迎我们串流使用。基于这种情况，我应该不会再更新这个插件了。

感謝大佬 我也有去問 ANI說RSS沒問題 我看一下
https://api.ani.rip/ani-download.xml  的內容是有更新的  不過最新內容在最下方
![image](https://github.com/user-attachments/assets/0ea4363f-c589-4af8-bd4f-8275e76dcc11)
可能API阻擋了插件拉取 個人去看是沒問題的

**Comment by honue** [comment]
回头我看看吧

**Comment by Awhitedressy** [comment]
这插件啥时候支持V2 ，今天v2更新beta了。
