### ISSUE TITLE
大佬能否更新适配下Tracker替换插件

### ISSUE THREAD

**Issue by XiaYi1002** [honue/MoviePilot-Plugins#64]
很巴适的一个插件，现在换v2了，才发现这个插件没有适配，自己fork的项目，加了"v2": true，但是没有周期执行选项，毕竟小白，也仅此而以了，能做到这也是极限了，So。。大佬有空之时，可否抽空完善下呢。非常感谢您的付出

**Comment by honue** [comment]
https://github.com/jxxghp/MoviePilot-Plugins/pull/526
