### ISSUE TITLE
自适应 introskip 这个插件能适配 v2 吗？

### ISSUE THREAD

**Issue by weidongzhou1994** [honue/MoviePilot-Plugins#65]
如题

**Comment by honue** [comment]
已经适配了吧

**Comment by weidongzhou1994** [comment]
安装的时候有点问题，安装不上
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/0fe674ef-4b1a-4483-ab79-3fcd6fcfd732">

**Comment by libashanxi** [comment]
同样安装不上

**Comment by honue** [comment]
确定排除了网络问题吗？

**Comment by libashanxi** [comment]
别的插件安装都正常，但是这个插件安装的时候显示是安装成功，实际上在我的插件里找不到

**Comment by weidongzhou1994** [comment]
> 确定排除了网络问题吗？

<img width="548" alt="image" src="https://github.com/user-attachments/assets/2fab53f9-41b1-4374-9710-b1eb1a2180a8">

**Comment by felix-klk** [comment]
同样存在这个问题

**Comment by felix-klk** [comment]
> 同样存在这个问题

显示安装成功 但是在我的插件里面并不能看见

**Comment by honue** [comment]
请配置EMBY_HOST变量

**Comment by weidongzhou1994** [comment]
加了，没啥反应，应该是 v2 支持多个媒体服务器导致的读取问题吧

**Comment by qin9125** [comment]
> 加了，没啥反应，应该是 v2 支持多个媒体服务器导致的读取问题吧

我也装不上，不知道作者为啥关闭了提问

**Comment by SSAXX22** [comment]
我提示安装成功，但是在安装好的插件里面看不到。

**Comment by Kluoke** [comment]
嗷呜
