### ISSUE TITLE
anistrm 

### ISSUE THREAD

**Issue by yangchris4** [honue/MoviePilot-Plugins#66]
师爷，我死活装不上4.2.2啊。
修改插件代码后，需要修改package.json中的version版本号，MoviePilot才会提示用户有更新，注意版本号需要与__init__.py文件中的plugin_version保持一致。
另外能不能提供自定义strm 选项，不填就默认用内置的dev网址，填就用自己的。

**Comment by honue** [comment]
>  另外能不能提供自定义strm 选项，不填就默认用内置的dev网址，填就用自己的。

这个我后面加下

**Comment by qin9125** [comment]
<img width="1665" alt="image" src="https://github.com/user-attachments/assets/69c5480b-214f-4dbe-8d4e-d307e7246904">


> > 另外能不能提供自定义strm 选项，不填就默认用内置的dev网址，填就用自己的。
> 
> 这个我后面加下

mp v2 提示安装成功，实际是装不上，

**Comment by yangchris4** [comment]
> > 另外能不能提供自定义strm 选项，不填就默认用内置的dev网址，填就用自己的。
> 
> 这个我后面加下

感谢，另外能不能自定义拉取不同季度的番剧呢，有些错过了想要再补一下
