### ISSUE TITLE
大佬求教下，显示“当前没有兼容的流。请稍后再试或联系您的管理员以获取详细信息。”该怎么办

### ISSUE THREAD

**Issue by 7-orion** [honue/MoviePilot-Plugins#7]
试了下strm文件里的连接可以直接在浏览器里访问，然后弹下载框
用的是软路由里的openclash，里面已添加两个域名设置代理规则
emby的环境变量里也有添加代理设置
<img width="852" alt="Snipaste_2024-02-19_21-28-12" src="https://github.com/honue/MoviePilot-Plugins/assets/32628296/f3a014ed-4d30-461e-bb06-8c0d213cf49a">

<img width="882" alt="Snipaste_2024-02-19_21-29-32" src="https://github.com/honue/MoviePilot-Plugins/assets/32628296/c8198065-20f5-4a5f-b1e9-8836c65cc6d9">
不知道是不是因为我的emby网络host的问题？纯小白希望大佬有空的时候能帮忙下 谢谢

**Comment by honue** [comment]
建议上emby的log

**Comment by honue** [comment]
位置在设置-服务器-日志 找到最新那个 embyserver.txt 最新日志会在这个文件的最下面

**Comment by honue** [comment]
你这是很早之前使用创建的strm吧？我看很多人fork我的项目把resource这个域名换成aniopen.an-i.workers.dev，所以我也在一周前换成这个域名了，你试试这个域名，具体我也不清楚，我这边是正常使用的.
![image](https://github.com/honue/MoviePilot-Plugins/assets/57806936/ea3fd927-1451-4151-9839-921ea73de93b)
