### ISSUE TITLE
大佬，不勾选创建当前季度就无法生成

### ISSUE THREAD

**Issue by yating1022** [honue/MoviePilot-Plugins#8]
勾选之后就正常，然后大佬我想生成所有的strm应该怎么操作

**Comment by honue** [comment]
有开关啊，支持生成当季全部的strm

**Comment by yating1022** [comment]
> 有开关啊，支持生成当季全部的strm

大佬，我是想生成2020-04到现在所有的strm，然后不勾选当季就不生成这个是正常的吗

**Comment by honue** [comment]
> 大佬，我是想生成2020-04到现在所有的strm，然后不勾选当季就不生成这个是正常的吗
不支持

**Comment by yating1022** [comment]
> > 大佬，我是想生成2020-04到现在所有的strm，然后不勾选当季就不生成这个是正常的吗
> 
> 不支持

好的感谢

**Comment by yating1022** [comment]
> > 大佬，我是想生成2020-04到现在所有的strm，然后不勾选当季就不生成这个是正常的吗
> 
> 不支持
