### ISSUE TITLE
bangumi插件修改已入库的番剧评分，只更新集评分不更新整体的剧集评分

### ISSUE THREAD

**Issue by jotaro167** [honue/MoviePilot-Plugins#9]
![6a96153f1a88195f50734d691d342c4a](https://github.com/honue/MoviePilot-Plugins/assets/127292049/b023a6bf-a365-46d7-96cb-92d963ae21d9)

**Comment by honue** [comment]
兄弟跑错库了，是这个兄弟的插件 HankunYu/MoviePilot-Plugins

**Comment by jotaro167** [comment]
> 兄弟跑错库了，是这个兄弟的插件 HankunYu/MoviePilot-Plugins

sry
